---
# handlers file for ec2_provision role

- name: Display provisioned instance info
  ansible.builtin.debug:
    msg: |
      Instance {{ item.instances[0].instance_id }} is available.
      Public IP: {{ item.instances[0].public_ip_address | default(item.instances[0].public_dns_name, true) | default('N/A', true) }}
      Name: {{ item.instances[0].tags.Name | default(item.item.name, true) }}
  loop: "{{ ec2_provision_result.results | default([]) }}"
  when:
    - ec2_provision_result is defined
    - item.instances | default([]) | length > 0
  listen: "Display instance info"
