all:
  children:
    debian_instances:
      hosts:
        <MANAGE-NODE-2-IP>:
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ./files/ssh_keys/my-ansible-key.pem
        <MANAGE-NODE-3-IP>:
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ./files/ssh_keys/my-ansible-key.pem
    redhat_instances:
      hosts:
        <MANAGE-NODE-1-IP>:
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ./files/ssh_keys/my-ansible-key.pem
