---
- hosts: localhost
  connection: local
  vars_files:
    - ../group_vars/all/pass.yml # ruta to your vault file with AWS credentials

  tasks:
    - name: Create EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        key_name: "my-ansible-key" # Replace with your key pair name
        instance_type: t2.micro
        security_group: ansible-sg-ssh # Replace with your security group name
        region: us-east-1
        aws_access_key: "{{ec2_access_key}}" # From vault as defined
        aws_secret_key: "{{ec2_secret_key}}" # From vault as defined
        network_interfaces:
          - assign_public_ip: true
            device_index: 0 # First interface (eth0 in Linux)
        image_id: "{{ item.image }}"
        tags:
          environment: "{{ item.name }}"
      loop:
        - { image: "ami-05ffe3c48a9991133", name: "manage-node-1" } # Update AMI ID according
        - { image: "ami-020cba7c55df1f615", name: "manage-node-2" } # to your account
        - { image: "ami-020cba7c55df1f615", name: "manage-node-3" }
