---
- hosts: redhat_instances
  become: true

  tasks:
    - name: Shutdown RedHat instances only
      ansible.builtin.command: /sbin/shutdown -t now
      when: ansible_facts['os_family'] == "RedHat"
